CREATE TABLE IF NOT EXISTS __schema__.bronze_azure_focus (
    "BilledCost" DOUBLE PRECISION,
    "BillingAccountId" TEXT,
    "BillingAccountName" TEXT,
    "BillingAccountType" TEXT,
    "BillingCurrency" TEXT,
    "BillingPeriodEnd" TEXT,
    "BillingPeriodStart" TEXT,
    "ChargeCategory" TEXT,
    "ChargeClass" DOUBLE PRECISION,
    "ChargeDescription" TEXT,
    "ChargeFrequency" TEXT,
    "ChargePeriodEnd" TEXT,
    "ChargePeriodStart" TEXT,
    "CommitmentDiscountCategory" DOUBLE PRECISION,
    "CommitmentDiscountId" TEXT,              -- Changed from DOUBLE PRECISION
    "CommitmentDiscountName" TEXT,            -- Changed from DOUBLE PRECISION
    "CommitmentDiscountStatus" DOUBLE PRECISION,
    "CommitmentDiscountType" DOUBLE PRECISION,
    "ConsumedQuantity" DOUBLE PRECISION,
    "ConsumedUnit" TEXT,
    "ContractedCost" DOUBLE PRECISION,
    "ContractedUnitPrice" DOUBLE PRECISION,
    "EffectiveCost" DOUBLE PRECISION,
    "InvoiceIssuerName" TEXT,
    "ListCost" DOUBLE PRECISION,
    "ListUnitPrice" DOUBLE PRECISION,
    "PricingCategory" TEXT,
    "PricingQuantity" DOUBLE PRECISION,
    "PricingUnit" TEXT,
    "ProviderName" TEXT,
    "PublisherName" TEXT,
    "RegionId" TEXT,
    "RegionName" TEXT,
    "ResourceId" TEXT,
    "ResourceName" TEXT,
    "ResourceType" TEXT,
    "ServiceCategory" TEXT,
    "ServiceName" TEXT,
    "SkuId" TEXT,
    "SkuPriceId" TEXT,
    "SubAccountId" TEXT,
    "SubAccountName" TEXT,
    "SubAccountType" TEXT,
    "Tags" TEXT,
    "x_AccountId" TEXT,                       -- Changed from DOUBLE PRECISION
    "x_AccountName" TEXT,                     -- Changed from DOUBLE PRECISION
    "x_AccountOwnerId" TEXT,                  -- Changed from DOUBLE PRECISION
    "x_BilledCostInUsd" DOUBLE PRECISION,
    "x_BilledUnitPrice" DOUBLE PRECISION,
    "x_BillingAccountId" TEXT,
    "x_BillingAccountName" TEXT,
    "x_BillingExchangeRate" BIGINT,
    "x_BillingExchangeRateDate" TEXT,
    "x_BillingProfileId" TEXT,
    "x_BillingProfileName" TEXT,
    "x_ContractedCostInUsd" DOUBLE PRECISION,
    "x_CostAllocationRuleName" TEXT,          -- Changed from DOUBLE PRECISION
    "x_CostCenter" TEXT,                      -- Changed from DOUBLE PRECISION
    "x_CustomerId" TEXT,                      -- Changed from DOUBLE PRECISION (HIGHLY LIKELY FIX)
    "x_CustomerName" TEXT,
    "x_EffectiveCostInUsd" DOUBLE PRECISION,
    "x_EffectiveUnitPrice" DOUBLE PRECISION,
    "x_InvoiceId" TEXT,                       -- Changed from DOUBLE PRECISION
    "x_InvoiceIssuerId" TEXT,                 -- Changed from DOUBLE PRECISION
    "x_InvoiceSectionId" TEXT,
    "x_InvoiceSectionName" TEXT,
    "x_ListCostInUsd" DOUBLE PRECISION,
    "x_PartnerCreditApplied" BIGINT,
    "x_PartnerCreditRate" BIGINT,
    "x_PricingBlockSize" BIGINT,
    "x_PricingCurrency" TEXT,
    "x_PricingSubcategory" TEXT,
    "x_PricingUnitDescription" TEXT,
    "x_PublisherCategory" TEXT,
    "x_PublisherId" TEXT,                     -- Changed from DOUBLE PRECISION
    "x_ResellerId" TEXT,                      -- Changed from DOUBLE PRECISION
    "x_ResellerName" TEXT,                    -- Changed from DOUBLE PRECISION
    "x_ResourceGroupName" TEXT,
    "x_ResourceType" TEXT,
    "x_ServicePeriodEnd" TEXT,
    "x_ServicePeriodStart" TEXT,
    "x_SkuDescription" TEXT,
    "x_SkuDetails" TEXT,
    "x_SkuIsCreditEligible" BOOLEAN,
    "x_SkuMeterCategory" TEXT,
    "x_SkuMeterId" TEXT,
    "x_SkuMeterName" TEXT,
    "x_SkuMeterSubcategory" TEXT,
    "x_SkuOfferId" DOUBLE PRECISION,
    "x_SkuOrderId" TEXT,
    "x_SkuOrderName" TEXT,
    "x_SkuPartNumber" DOUBLE PRECISION,
    "x_SkuRegion" TEXT,
    "x_SkuServiceFamily" TEXT,
    "x_SkuTerm" DOUBLE PRECISION,
    "x_SkuTier" DOUBLE PRECISION,
    "hash_key" TEXT PRIMARY KEY 
);