CREATE TABLE IF NOT EXISTS __schema__.bronze_focus_gcp_data (
    "hash_key" TEXT PRIMARY KEY, -- Unique and primary key
    "AvailabilityZone" TEXT,
    "BilledCost" TEXT,
    "BillingAccountId" TEXT,
    "BillingCurrency" TEXT,
    "BillingPeriodStart" TIMESTAMP WITH TIME ZONE,
    "BillingPeriodEnd" TIMESTAMP WITH TIME ZONE,
    "ChargeCategory" TEXT,
    "ChargeClass" TEXT,
    "ChargeDescription" TEXT,
    "ChargePeriodStart" TIMESTAMP WITH TIME ZONE,
    "ChargePeriodEnd" TIMESTAMP WITH TIME ZONE,
    "CommitmentDiscountCategory" TEXT,
    "CommitmentDiscountId" TEXT,
    "CommitmentDiscountName" TEXT,
    "ConsumedQuantity" TEXT,
    "ConsumedUnit" TEXT,
    "ContractedCost" TEXT,
    "ContractedUnitPrice" TEXT,
    "EffectiveCost" TEXT,
    "ListCost" TEXT,
    "ListUnitPrice" TEXT,
    "PricingCategory" TEXT,
    "PricingQuantity" TEXT,
    "PricingUnit" TEXT,
    "ProviderName" TEXT,
    "PublisherName" TEXT,
    "RegionId" TEXT,
    "RegionName" TEXT,
    "ResourceId" TEXT,
    "ResourceName" TEXT,
    "ResourceType" TEXT,
    "ServiceCategory" TEXT,
    "ServiceName" TEXT,
    "SkuId" TEXT,
    "SkuPriceId" TEXT,
    "SubAccountId" TEXT,
    "Tags" TEXT,
    "x_Credits" TEXT,
    "x_CostType" TEXT,
    "x_CurrencyConversionRate" TEXT,
    "x_ExportTime" TIMESTAMP WITH TIME ZONE,
    "x_Location" TEXT,
    "x_ProjectId" TEXT,
    "x_ProjectNumber" TEXT,
    "x_ProjectName" TEXT,
    "x_ProjectAncestryNumbers" TEXT,
    "x_ProjectAncestors" TEXT,
    "x_Project" TEXT,
    "x_ServiceId" TEXT
);
