CREATE TABLE if not exists __schema__.silver_focus_aws (
	"hash_key" text primary key,
    "AvailabilityZone" text,
    "BilledCost" double precision,
    "BillingAccountId" text,
    "BillingAccountName" text,
    "BillingCurrency" text,
    "BillingPeriodEnd" timestamp without time zone,
    "BillingPeriodStart" timestamp without time zone,
    "ChargeCategory" text,
    "ChargeClass" text,
    "ChargeDescription" text,
    "ChargeFrequency" text,
    "ChargePeriodEnd" timestamp without time zone,
    "ChargePeriodStart" timestamp without time zone,
    "CommitmentDiscountCategory" text,
    "CommitmentDiscountId" text,
    "CommitmentDiscountName" text,
    "CommitmentDiscountStatus" text,
    "CommitmentDiscountType" text,
    "ConsumedQuantity" double precision,
    "ConsumedUnit" text,
    "ContractedCost" double precision,
    "ContractedUnitPrice" double precision,
    "EffectiveCost" double precision,
    "InvoiceIssuerName" text,
    "ListCost" double precision,
    "ListUnitPrice" double precision,
    "PricingCategory" text,
    "PricingQuantity" double precision,
    "PricingUnit" text,
    "ProviderName" text,
    "PublisherName" text,
    "RegionId" text,
    "RegionName" text,
    "ResourceId" text,
    "ResourceName" text,
    "ResourceType" text,
    "ServiceCategory" text,
    "ServiceName" text,
    "SkuId" text,
    "SkuPriceId" text,
    "SubAccountId" text,
    "SubAccountName" text,
    "Tags" text,
    "x_CostCategories" text,
    "x_Discounts" text,
    "x_Operation" text,
    "x_ServiceCode" text,
    "x_UsageType" text
);
